import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { LineChart, Upload, Filter, BarChart2 } from 'lucide-react'
import { getVisualizations } from '../utils/api'
import { useStore } from '../store'
import { LoadingState, EmptyState } from '../components/ui'
import PlotlyChart from '../components/charts/PlotlyChart'
import clsx from 'clsx'

const CHART_TYPES = ['all', 'histogram', 'boxplot', 'heatmap', 'scatter', 'bar', 'violin', 'pie', 'line']

export default function VisualizePage() {
  const navigate = useNavigate()
  const currentDataset = useStore((s) => s.currentDataset)

  const [charts, setCharts] = useState([])
  const [loading, setLoading] = useState(true)
  const [filter, setFilter] = useState('all')
  const [error, setError] = useState('')

  useEffect(() => {
    if (!currentDataset) return
    load()
  }, [currentDataset])

  const load = async () => {
    setLoading(true)
    setError('')
    try {
      const { data } = await getVisualizations(currentDataset.id)
      setCharts(data.charts || [])
    } catch (e) {
      setError(e.message)
    } finally {
      setLoading(false)
    }
  }

  if (!currentDataset) {
    return (
      <EmptyState
        icon={Upload}
        title="No dataset selected"
        description="Upload a dataset to see visualizations."
        action={<button onClick={() => navigate('/upload')} className="btn-primary">Upload Dataset</button>}
      />
    )
  }

  if (loading) return <LoadingState message="Generating visualizations..." />

  const filtered = filter === 'all' ? charts : charts.filter((c) => c.chart_type === filter)
  const available = [...new Set(charts.map((c) => c.chart_type))]

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="page-header">
        <h1 className="page-title">Visualization Dashboard</h1>
        <p className="page-subtitle">
          {charts.length} charts auto-generated by the Visualization Agent
        </p>
      </div>

      {/* Filter chips */}
      <div className="flex flex-wrap gap-2 items-center">
        <Filter size={14} className="text-surface-500" />
        {CHART_TYPES.filter((t) => t === 'all' || available.includes(t)).map((type) => (
          <button
            key={type}
            onClick={() => setFilter(type)}
            className={clsx(
              'px-3 py-1.5 rounded-full text-xs font-medium transition-all capitalize',
              filter === type
                ? 'bg-brand-500 text-white'
                : 'bg-surface-800 text-surface-400 hover:text-surface-200 border border-surface-700'
            )}
          >
            {type}
            {type !== 'all' && (
              <span className="ml-1.5 opacity-60">
                {charts.filter((c) => c.chart_type === type).length}
              </span>
            )}
          </button>
        ))}
        {filter !== 'all' && (
          <span className="text-surface-500 text-xs ml-2">
            {filtered.length} chart{filtered.length !== 1 ? 's' : ''}
          </span>
        )}
      </div>

      {error && (
        <div className="card border-red-500/30 text-red-400 text-sm">
          {error}
        </div>
      )}

      {filtered.length === 0 && !error && (
        <EmptyState
          icon={BarChart2}
          title="No charts for this filter"
          description="Try selecting 'all' or run EDA first."
        />
      )}

      {/* Charts grid */}
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
        {filtered.map((chart, i) => (
          <motion.div
            key={`${chart.chart_type}-${i}`}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.05 }}
          >
            <PlotlyChart
              plotlyJson={chart.plotly_json}
              title={chart.title}
              reason={chart.reason}
            />
          </motion.div>
        ))}
      </div>

      {/* Full-width charts (heatmap) */}
      {charts
        .filter((c) => c.chart_type === 'heatmap')
        .filter((_, i) => (filter === 'all' || filter === 'heatmap') && filtered.find((f) => f === _))
        .slice(0, 0) /* already shown above */
        .map((chart, i) => (
          <PlotlyChart
            key={`heatmap-full-${i}`}
            plotlyJson={chart.plotly_json}
            title={chart.title}
            reason={chart.reason}
            className="col-span-2"
          />
        ))}
    </div>
  )
}
